### Week 5 Homework

1. What does Pandas stand for?
* Derived from 'Panel Data'. References 'Python Data Analysis Library'
2. What are the 2 collections used in Pandas?
* Series: 1-dimension & DataFrame: 2-dimensional
3. Name 4 things Pandas can do for us
* Load, manipulate, prepare & model
4. To permanently sort a DataFrame, which keyword should one use with the `df.sort()` method?
* Inplace = true
5. What is a CSV
* A delimited text file that uses commas to separate values (comma separated values)
6. When cleaning data what values do we not like in our data?
* Null values


In [2]:
# Coding 

# 1. Concatenate these 3 arrays into a new array named 'newArray'
import numpy as np

# Define the 3 arrays
array1 = np.array([[25, 16]])
array2 = np.array([[11, 2], [13, 4]])
array3 = np.array([[7, 81], [5, 6], [11, 12]])

# Concat the arrays
newArray = np.concatenate((array1, array2, array3), axis=0)
print("\nnewArray is:\n", newArray)

# 2. Sort 'newArray' in order into 'sortedArray'
sortedArray = np.sort(newArray)
print("\nsortedArray is:\n", sortedArray)

# 3. Reshape'sortedArray' array, into new array called 'reshapedArray', has 2 dimensions with a size of 2, 3.
reshapedArray = np.reshape(sortedArray, (2, 2, 3))
print("\nreshapedArray is:\n", reshapedArray)

# 4. Unpack array tuples from above 'reshapedArray' into 4 well named variables. Print variables

# Keep getting error using reshapedArray from above, so reshaping again
ReshapedArray = np.reshape(reshapedArray, (4, 3))

# Unpack array tuples with new variables
var1, var2, var3, var4 = ReshapedArray
print("\nvar1 is:", var1)
print("\nvar2 is:", var2)
print("\nvar3 is:", var3)
print("\nvar4 is:", var4)

# New code block below for remaining questions



newArray is:
 [[25 16]
 [11  2]
 [13  4]
 [ 7 81]
 [ 5  6]
 [11 12]]

sortedArray is:
 [[16 25]
 [ 2 11]
 [ 4 13]
 [ 7 81]
 [ 5  6]
 [11 12]]

reshapedArray is:
 [[[16 25  2]
  [11  4 13]]

 [[ 7 81  5]
  [ 6 11 12]]]

var1 is: [16 25  2]

var2 is: [11  4 13]

var3 is: [ 7 81  5]

var4 is: [ 6 11 12]


In [1]:
# 5. Combined and sort the following arrays into one called 'comboArray'
import numpy as np
# list arrays
one = ([10, 11, 12, 13, 14, 15, 16, 17])
two = ([20, 21, 22, 23, 24, 25, 26, 27])
three = ([ 0, 1, 2, 3, 4, 5, 6, 7])

# combine & sort arrays
comboarray = np.concatenate((one, two, three), axis=0)
comboArray = np.sort(comboarray)
print(comboArray)

# 6. Take 'comboArray' and perform the following slicing activities
print("\nLength of comboArray:", len(comboArray))
# print sec1 - the 2nd element
print("\nSec1:", comboArray[1])
# print sec 2 - all elements from 3rd to last
print("\nSec2:", comboArray[2:])
# print sec3 - all elements from the 4th to the 14th elements
print("\nSec 3:", comboArray[3:14])
# print sec4 - last 6 elements
print("\nSec 4:", comboArray[-6:])
# print sec5 - all element from #0 up to and including #15, using the negative number method
print("\nSec 5:", comboArray[:-10])
# print sec6 - from #20 every even element to the end
print("\nSec 6:", comboArray[16::2])
# print sec7 - from the last element moving forward, every 5th element
print("\nSec 7:", comboArray[-1::-5])

# 7. Using simple math operations, broadcast the addition `(+)`, division `(/)`, and multiplication `(*)` operations for these 2 arrays
from numpy import array
# Define arrays
arr1 = array([[[ 0.0,  0.0,  0.10], [10.0, 10.30, 10.01]],
        [[20.0, 20.02, 20.10], [30.0, 31.0, 30.30]],
        [[40.40, 24.0, 40.0], [15.0, 15.5, 25.5]]])
arr2 = array([[17.0, 70.0, 10.7]])

print("\nAddition:\n", arr1 + arr2)
print("\nDivision:\n", arr1 / arr2)
print("\nMultiplication:\n", arr1 * arr2)

# 8. Use the NumPy Arithmetic functions to do the subtraction of the above two arrays in point #7.
print("\nSubtraction:\n", np.subtract(arr1, arr2))





[ 0  1  2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]

Length of comboArray: 24

Sec1: 1

Sec2: [ 2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]

Sec 3: [ 3  4  5  6  7 10 11 12 13 14 15]

Sec 4: [22 23 24 25 26 27]

Sec 5: [ 0  1  2  3  4  5  6  7 10 11 12 13 14 15]

Sec 6: [20 22 24 26]

Sec 7: [27 22 15 10  3]

Addition:
 [[[ 17.    70.    10.8 ]
  [ 27.    80.3   20.71]]

 [[ 37.    90.02  30.8 ]
  [ 47.   101.    41.  ]]

 [[ 57.4   94.    50.7 ]
  [ 32.    85.5   36.2 ]]]

Division:
 [[[0.         0.         0.00934579]
  [0.58823529 0.14714286 0.93551402]]

 [[1.17647059 0.286      1.87850467]
  [1.76470588 0.44285714 2.8317757 ]]

 [[2.37647059 0.34285714 3.73831776]
  [0.88235294 0.22142857 2.38317757]]]

Multiplication:
 [[[0.00000e+00 0.00000e+00 1.07000e+00]
  [1.70000e+02 7.21000e+02 1.07107e+02]]

 [[3.40000e+02 1.40140e+03 2.15070e+02]
  [5.10000e+02 2.17000e+03 3.24210e+02]]

 [[6.86800e+02 1.68000e+03 4.28000e+02]
  [2.55000e+02 1

In [10]:
# 9. Using modulo find all elements that are divisible by 3 from the multi-dimensional array under point #7 above
divisible_by_3 = arr1[arr1 % 3 == 0]
print("|nDivisible by 3:\n", divisible_by_3)

# 10 Using `Series`, create a `DataFrame` that looks like this:
import pandas as pd
# Create series info.
I = pd.Series(['Flour', 'Milk', 'Eggs', 'Spam'], name= "Ingredients")
Q = pd.Series([4, 1, 2, 1], name= "Quantity")
U = pd.Series(['cups', 'cup', 'large', 'can'], name= "unit")

#concat & name DataFrame
df = pd.concat([I, Q, U], axis=1)
df.name = "Dinner"
print(df)

# 11. Take this data and create a DataFrame named studentData
studentData = {'Name': ['Jai', 'janusha', 'Gaurav', 'Anuj'],
        'Height': [5.1, 6.2, 5.1, 5.2],
        'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
        'address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'],
        'Age': [21, 23, 24, 21],
        'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
        'sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']
    }
studentData = pd.DataFrame(studentData)
studentData.name = "studentData"
print("\nDataframe names: studentData:\n", studentData)

# 12. Add a new column to the DataFrame with the following deserts:["ice cream", "Cashew Fudge",
#  "waffels", "Carrot Halwa"]
studentData.insert(7, "Deserts", ["ice cream", "cashew Fudge", "waffles", "Carrot Halwa"])
print("\nInsert dedsert column:\n", studentData)

# 13. Sort the 'studentData' DataFrame in Ascending order -- Sorting by column 'Name' and then "address"
studentData.sort_values(by = ['Name', 'address'], inplace = True)
print("\nSort by 'Name' & 'address':\n", studentData)

|nDivisible by 3:
 [ 0.  0. 30. 24. 15.]
  Ingredients  Quantity   unit
0       Flour         4   cups
1        Milk         1    cup
2        Eggs         2  large
3        Spam         1    can

Dataframe names: studentData:
       Name  Height Qualification  address  Age        Pets           sport
0      Jai     5.1           Msc    Delhi   21         Dog           Darts
1  janusha     6.2            MA     Doha   23       Bunny      Basketball
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket

Insert dedsert column:
       Name  Height Qualification  address  Age        Pets           sport  \
0      Jai     5.1           Msc    Delhi   21         Dog           Darts   
1  janusha     6.2            MA     Doha   23       Bunny      Basketball   
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding   
3     Anuj     5.2           Msc   Dakhar   21      Parrot  

In [9]:
import pandas as pd
# 14. Save this `DataFrame` here below to disc as a `.CSV` file with the name `cows_and_goats.csv`:
df = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])
df.to_csv('cows_and_goats.csv', index=True)

# 15A. Using Pandas, make your own .CSV file with data on vegetables and save it
vegetables = pd.DataFrame([["carrot", "orange"], ["celery", "green"], ["tomato", "red"], ["corn", "yellow"]],
                          columns=["Vegetable", "Color"])
vegetables.to_csv('vegetables.csv')

# 15B. #Using Pandas, make a change to the CSV file, and save a copy with a different name 
# Create new DataFrame name with copy of same data from 'vegetables'
vegetables_with_calories = vegetables.copy()

# Add column 'Calories', how many calories in one cup of each vegetable
vegetables_with_calories['Calories'] = [45, 14, 32, 132 ]

# Save updated DataFrame as new CSV file with different name
vegetables_with_calories.to_csv('vegetables_with_calories.csv', index=True)

# Print both DataFrames
print(vegetables)

print(vegetables_with_calories)

  Vegetable   Color
0    carrot  orange
1    celery   green
2    tomato     red
3      corn  yellow
  Vegetable   Color  Calories
0    carrot  orange        45
1    celery   green        14
2    tomato     red        32
3      corn  yellow       132
