## Questions

1. What does one need to do to use a module?
    * You need to import that module into your program

1. Name a Module (not the DateTime Nodule) we looked at and write a line or 2 of code as an example using this module.
    * Another module we discussed was the random module used to give random numbers
    * Example code:

#####import random
#####randomNo = random.randrange(1,15)
#####print(randomNo)

1. What is a benefit of using Exception handling?
    * It allows for the code to keep running instead of crashing even if there is an error. Some examples are you can test blocks of code, handle the error, or execute the code when there is no error.

1. NumPy arrays are like what Python data type?
    * Lists

1. What is one of the main benefits of using NumPy arrays.
    * It occupies less memory and is much faster than python lists

1. What is one of the main requirements about the 'dtype' of NumPy arrays?
    * It needs to be the same data type 

1. Of the 10 uses of NumPy, name 2.
    * Arithmetic operations and copying & viewing arrays

1. Name one of the other libraries we'll use with NumPy?
    * Matplotlib

1. What is the shape of NumPy arrays?
    * The number of elements in each dimension

1. What is a Tensor?
    * An array with 3+ dimensions

1. Name a reason why it's better using  NumPy for Data Analysis than using a Python List?
    * It is faster and more efficient while also using less memory
    
1. When creating an "empty" array, where do the elements come from?
    * The empty value will contain whatever was already in the memory location of the array and will get the elements from there

In [8]:
# 1. Use the DateTime module to get Current Date and Time, and save it to a variable
import datetime as dt
x = dt.datetime.now()
print(x)

# Extract just full month name from that variable
month = dt.datetime.now()
print("Month:", month.strftime("%B"))


# 2. Write a simple function that takes 2 parameters -- a  first name and a day name.
def greetings(name, day = "Sunday"):
    print("Hi", name,"! Happy", day,"!")

# Invoke with two variables
greetings("David", "Tuesday")

# Invoke with one variable
greetings("John")

2023-02-13 21:54:26.311649
Month: February


In [3]:
# 3. Import NumPy
import numpy as np

# create array with shape (2, 3, 2) using reshape method
array = np.arange(12).reshape(2, 3, 2)
print(array)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


In [8]:
# 4. Use NumPy `.linspace()` to create an array with 6 linearly spaced values between 0 and 20
import numpy as np
array1 = np.linspace(0,20, num = 6)
print(array1)


# 5. Make deep copy
import copy
array2 = copy.deepcopy(array1)


# 6. What are 2 reasons we use NumPy arrays over Python Lists?
    # Numpy arrays are faster and more efficient than Python lists while also occupying less memory.

[ 0.  4.  8. 12. 16. 20.]
